## TF-IDF
https://www.youtube.com/watch?v=ngYeCV57GlQ&t=45s

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
text =['비자는 꼭, 무슨 일이 있어도 한국에서 받아오세요. 출국 한달 전에 비자 받으려고 했다가 구비 서류 다 준비 못해서 (한국에서 받으실거면 미리미리 대사관 예약하고 받으세요 예약 2주 기다려야합니다ㅜㅜ)그냥 독일에서 받아야지 하고 갔는데 독일 일처리 진짜 늦어서 저희는 나오는데 두세달 걸렸어요ㅠㅠ 비자 없으면 슈페어콘토도 안나와서 세달동안 돈도 못받고 지냈어요ㅠㅠ 그래도 독일에서 받으실거라면 초반에 오리엔테이션기간에 학교에서 알아서 해주긴 해요. 근데 학교에서 하지 마시고 직접 외국인청 가셔서 테어민 잡으시고 만드는게 훨씬 빠르실거에요! 독일 일처리 진짜 느리고 자기네들 멋대로에요, 되도록 모든 서류 절차는 빠르고 신속하고 정확한 한국에서 해가시는걸 추천드립니다!',
      '일단 미컴과나 미디어 관련 수업을 들으시면 학교에서 본교랑 가까운 기숙사 말고 역 근처 집으로 배정해주는 것 같아요! 그래서 아무래도 본교 기숫사에 배정된 다른 한국인 친구들과 좀 먼 곳에서 살수도 있어요. 제가 살던 집이 본교랑은 멀고 역이랑은 가까운 5명이 같이 사는 쉐어하우스였는데 저는 매우 만족했습니다! 일단 집은 제가 본 독일 집중에 제일 꾸졌었는데 같이 살던 쉐어하우스 친구들이 너무 좋아서 좋았습니다! 저는 이탈리아, 멕시코, 일본, 미국 친구들이랑 살았어요! 다 너무 착해서 같이 술도 많이 먹고 종강 후에는 여행도 같이 다녔습니다! 영어도 많이 써서 꽤 늘었던 것 같아요. 근데 제가 운 좋게 같이 사는 친구들이 좋았고 안 맞는 경우도 많아서 완전 운인 것 같아요. 아 근데 저희 집은 혼성이었어요! 원래 혼성 쉐어하우스가 진짜 재미있다는 얘기를 듣고 가서 기대 많이 했는데 역시 재미있었습니다! 혼성이라고 크게 불편하진 않았어요. 혼성 싫으시면 기숙사 신청하실 때 싫다고 선택하시면 됩니다.그리고 저희 집은 쉐어하우스 두개가 붙어있는데 두 집에 한국인을 한명씩은 배정해주는 것 같아요! 그래서 옆집 친구랑 맨날 같이 한식 해먹고 좋았습니다! 뒷마당도 있어서 파티할 때도 좋고 그냥 날씨 좋으면 선배드에 누워서 여행계획 짜는 것도 참 행복했습니다ㅠㅠ 그리고 집에서 좀만 걸어가면 완전 넓은 수영장도 있어요!! 본교 갈때는 버스를 한번 갈아타서 넉넉잡아 사십분정도 걸리고, 버스 막차가 8시반이라 시내에서 술 마시면 30분을 걸어와야 하지만 그 정도는 다 감수할 수 있을 만큼 좋은 집이었습니다! 외국인 친구들이랑 친해지고 싶으시다면 이 집 추천드려요!',
      '정말 너무너무 행복한 6개월이었어요. 원래 교환학생에 대한 로망도 없었고 가고 싶은 생각도 없었는데 간거였는데도 너무 만족했습니다. 학교 수업 같은 경우는 만족스러운 수업은 한 개밖에 없긴 했지만 저는 공부가 그렇게 큰 목적은 아니였어서..ㅎ 그냥 한국 수업 같은 느낌이었구요,  저는 시간표가 진짜 이래도 되나 싶을 정도로 많이 널널했어서 여행을 정말 많이 다녔습니다.(다시 한번 강조하지만 미컴과시라면 로이파나로 오세요!) 이주 여행하고 이주 쉬고 다시 여행하고 쉬고의 반복이었어요. 중간에는 엄마랑 오빠도 와서 3주동안 같이 여행했습니다! 저희 학교가 독일이어도 북쪽이라 위치가 엄청나게 좋다고 보기는 힘들어요. 독일 중에서 여행 다니기 좋은 도시는 베를린이에요! 비행기 값이 훨씬 싸더라구요! 학교 선택하실 때 참고하세요! 저는 그래서 일부러 베를린까지 플릭스 버스 타고 비행기는 베를린에서 타기도 했어요. 학교 생활은 국제처에서 프로그램들을 많이 제공해서 다른 나라 친구들과 친해질 기회를 많이 만들어줘요! 열심히 참여하시면 친해지실 수 있습니다. 독일은 파티가 정말 많아요. 근데 초대받은 사람만 가는게 아니라 파티가 있으면 가고 싶은 사람들은 그냥 막 가면 되는 문화라 그런 파티에 많이 가시면 외국인 친구들 많이 사귈 수 있습니다! 근데 언어가 생각보다 스트레스에요. 친해지는 건 가능해도 언어가 딸려서 깊은 대화가 불가능해서 한계를 많이 느꼈습니다. 저는 오시기 전에 괜히 독일어 공부하는 것 보다 영어 회화 공부 하시는걸 추천드려요. 한국인 빼고는 영어를 다 잘해서 자괴감 많이 들어요..ㅎㅎ 그래서 한국인들끼리 더 돈독해지기도 하는데요, 저희는 한국인이 10명이었는데 정말 너무 잘 지내서 행복했어요. 서로 집에 초대해서 한식 거하게 해먹고 같이 수영장도 가고 초등학교 때 동네 친구들이랑 노는 느낌으로 건전하고 순수(?) 하게 놀 수 있는 시간이었어요! 외국인들이랑 노는 것도 재미있었지만 한국인 친구들과 돈독하게 지낸 것도 정말 좋았습니다.  그리고 뤼네부르크는 시골동네라 정말 할게 없어요! 그래서 늦잠 자고 일어나서 밥 해먹고 빈둥대고 여행 계획 짜다가 밤에 맥주 먹고 잠드는게 일상이었습니다. 정말 한국에서는 상상도 못할 여유로움을 느끼실 수 있을거에요 ㅎㅎ 이제 취업하면 다신 느끼지 못할 자유와 여유 실컷 누리시다가 갈 수 있어요ㅠㅠ 그리고 여행 정말 많이 다니세요! 유럽에 오셨다면 남는 건 여행 뿐 입니다. 저는 학기 중에 시간이 많아서 유럽 거의 다 돌았는데 종강하고도 비행기 때문에 한달이 남아서 그리스까지 가고 모로코(아프리카)도 다녀왔어요ㅎㅎ 시간표 여유롭게 짜셔서 여행 뽕 뽑고 오세요!']

In [3]:
tfidf_vectorizer = TfidfVectorizer()

In [4]:
# 처음에 text 데이터를 학습시킬 때 fit 사용
tfidf_vectorizer.fit(text)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [5]:
# 단어사전 (실제로 파이썬 딕셔너리)
sorted(tfidf_vectorizer.vocabulary_.items())

[('10명이었는데', 0),
 ('2주', 1),
 ('30분을', 2),
 ('3주동안', 3),
 ('5명이', 4),
 ('6개월이었어요', 5),
 ('8시반이라', 6),
 ('ㅎㅎ', 7),
 ('가고', 8),
 ('가까운', 9),
 ('가는게', 10),
 ('가능해도', 11),
 ('가면', 12),
 ('가서', 13),
 ('가셔서', 14),
 ('가시면', 15),
 ('간거였는데도', 16),
 ('갈때는', 17),
 ('갈아타서', 18),
 ('감수할', 19),
 ('값이', 20),
 ('갔는데', 21),
 ('강조하지만', 22),
 ('같아요', 23),
 ('같은', 24),
 ('같이', 25),
 ('개밖에', 26),
 ('거의', 27),
 ('거하게', 28),
 ('건전하고', 29),
 ('걸렸어요ㅠㅠ', 30),
 ('걸리고', 31),
 ('걸어가면', 32),
 ('걸어와야', 33),
 ('것도', 34),
 ('경우는', 35),
 ('경우도', 36),
 ('계획', 37),
 ('곳에서', 38),
 ('공부', 39),
 ('공부가', 40),
 ('공부하는', 41),
 ('관련', 42),
 ('괜히', 43),
 ('교환학생에', 44),
 ('구비', 45),
 ('국제처에서', 46),
 ('그냥', 47),
 ('그래도', 48),
 ('그래서', 49),
 ('그런', 50),
 ('그렇게', 51),
 ('그리고', 52),
 ('그리스까지', 53),
 ('근데', 54),
 ('근처', 55),
 ('기다려야합니다ㅜㅜ', 56),
 ('기대', 57),
 ('기숙사', 58),
 ('기숫사에', 59),
 ('기회를', 60),
 ('깊은', 61),
 ('꾸졌었는데', 62),
 ('나라', 63),
 ('나오는데', 64),
 ('날씨', 65),
 ('남는', 66),
 ('남아서', 67),
 ('너무', 68),
 ('너무너무', 69),
 ('넉넉잡아', 70

In [6]:
# 위에서 구한 vocabulary마다 구해진 idf 값들
tfidf_vectorizer.idf_

array([1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.28768207, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.28768207,
       1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718, 1.        , 1.69314718, 1.28768207,
       1.69314718, 1.69314718, 1.28768207, 1.69314718, 1.        ,
       1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718, 1.69314718, 1.28768207, 1.69314718,
       1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314

In [7]:
# 아까 fit한 모델을 가져와서 쓰고싶을 때 transform
# 리스트 표시 []를 기준으로 하나의 도큐먼트로 구분
tfidf_vectorizer.transform(text).toarray()

array([[0.        , 0.10339704, 0.        , ..., 0.        , 0.07863612,
        0.        ],
       [0.        , 0.        , 0.06419568, ..., 0.06419568, 0.        ,
        0.        ],
       [0.04678994, 0.        , 0.        , ..., 0.        , 0.03558495,
        0.04678994]])

## TF-IDF SCORING
https://m.blog.naver.com/vangarang/221072014624

In [8]:
from collections import defaultdict

# corpus = ['동해물과 백두산이 마르고 닳도록 하느님이 보우하사 우리나라 만세 무궁화 삼천리 화려 강산 대한사람 대한으로 길이 보전하세',
#           '남산 위에 저 소나무 철갑을 두른 듯 바람서리 불변함은 우리 기상일세 무궁화 삼천리 화려 강산 대한사람 대한으로 길이 보전하세',
#           '가을 하늘 공활한데 높고 구름 없이 밝은 달은 우리 가슴 일편단심일세 무궁화 삼천리 화려 강산 대한사람 대한으로 길이 보전하세',
#           '이 기상과 이 맘으로 충성을 다하여 괴로우나 즐거우나 나라 사랑하세 무궁화 삼천리 화려 강산 대한사람 대한으로 길이 보전하세',
#           '오 필승 코리아 오 필승 코리아 오 필승 코리아 오 오레 오레 무궁화 삼천리 화려 강산 대한사람 대한으로 길이 보전하세']

# ============================================
# -- Get TFIDF
# ============================================
vectorizer = TfidfVectorizer()
sp_matrix = vectorizer.fit_transform(text)
sp_matrix.toarray()

array([[0.        , 0.10339704, 0.        , ..., 0.        , 0.07863612,
        0.        ],
       [0.        , 0.        , 0.06419568, ..., 0.06419568, 0.        ,
        0.        ],
       [0.04678994, 0.        , 0.        , ..., 0.        , 0.03558495,
        0.04678994]])

In [9]:
word2id = defaultdict(lambda : 0)
for idx, feature in enumerate(vectorizer.get_feature_names()):
    word2id[feature] = idx

result_dict = {}
for i, sent in enumerate(text):
    for token in sent.split():
        result_dict[token] = sp_matrix[i, word2id[token]]

### 중간 결론  
단어 기준 토큰화가 필요하다

## TF-IDF 한글 키워드 추출기  
https://m.blog.naver.com/vangarang/221075347600

In [10]:
from math import log10
from konlpy.tag import Okt

In [11]:
def f(t, d):
    # d is document == tokens
    return d.count(t)

In [12]:
def tf(t, d):
    # d is document == tokens
    return 0.5 + 0.5*f(t,d)/max([f(w,d) for w in d])

In [13]:
def idf(t, D):
    # D is documents == document list
    numerator = len(D)
    denominator = 1 + len([ True for d in D if t in d])
    return log10(numerator/denominator)

In [14]:
def tfidf(t, d, D):
    return tf(t,d)*idf(t, D)

In [15]:
def tokenizer(d): 
    okt=Okt()
    def keyword_extractor(text):
        tokens = okt.pos(text, stem=True) # 단어 기준
        result_tokens = []
        for token in tokens: # 한 글자인 단어 제외, 명사, 동사, 형용사만 키워드로 포함
            if ((len(token[0]) > 1) and (token[1] == 'Noun' or token[1] == 'Verb' or token[1] == 'Adjective')):
                result_tokens.append(token[0])
        print(result_tokens)
        count_dict = [(token, text.count(token)) for token in result_tokens]
        ranked_words = sorted(count_dict, key=lambda x: x[1], reverse=True)[:20]
        return [keyword for keyword, freq in ranked_words]
    return keyword_extractor(d)

In [16]:
def tfidfScorer(D):
    tokenized_D = [tokenizer(d) for d in D]
    result = []
    for d in tokenized_D:
        result.append([(t, tfidf(t, d, tokenized_D)) for t in d])
    return result

In [17]:
corpus = ['소문과 같이 네덜란드는 비바람이 많은 나라이다. 어디를 가든 자전거를 타게 되고 대부분의 날들은 비가 온다. 그래서 우비를 챙겨가거나 가서 사는 것을 추천한다. 네덜란드는 더치라고 그들의 언어가 따로 있지만 EU에서 영어를 가장 많이 쓰는 나라이다. 그래서 생활하는 데에 있어 언어로 큰 불편함은 없다. 한국에서의 생활은 매우 바쁘고 정신없었다. 특히 통학하는 학기이면 출근 시간에 지하철을 타야 했으며 쉬지 않는 생활을 하게 된다. 하지만 네덜란드로 교환학생을 하면서 여유롭고 평화로운 생활을 할 수 있게 되었다. 학교 수업은 다양하게 많은 양의 학업을 하는 것이 아니라 하나의 프로젝트를 집중적으로 일하며 하나가 끝이나면 다음 프로젝트로 넘어갔다. 이러한 학업 방식을 통해서 더 많은 것을 배울 수 있었고 집중력도 향상했다. 여유를 누리면서 학업에 더 전념할 수 있는 생활을 하게 되었다.',
         '개인적으로 학교 수업을 통해 지식적 측면에서 크게 얻어 가는 것은 없었던 것 같습니다. 그러나 네덜란드의 지리적 특성상 주변국으로 자유롭게 여행을 다닐 수 있다는 점, 철도 시설이 잘 갖추어져 있어 근교 도시를 방문하기 편하다는 점, 그리고 외국인 친구들과 교류할 기회를 만들 수 있다는 점이 가장 즐거웠던 요소들입니다. 실제로 주말마다 새로 사귄 친구들과 로테르담, 헤이그 등 주변 도시로 기차를 타고 여행을 떠났으며 가을 방학, 크리스마스 방학마다 프랑스, 독일, 스웨덴, 스위스 등 여러 국가들을 방문하곤 했습니다. 또한 네덜란드 사람들은 영어를 굉장히 잘하고 대부분 친절해 더치를 할 줄 몰라도 생활하는데 전혀 어려움이 없었습니다. 이러한 이유에서 네덜란드를 교환 대상 국가로 추천하고 싶습니다. 학생 신분으로 타국에 나가 혼자 살아 보고 또 자유롭게 여행을 다니는 경험은 쉽게 겪을 수 없는 것입니다. 힘든 점도 많았지만 즐거운 추억이 훨씬 많고 다시 돌이켜 보아도 교환을 떠날 것이라는 생각이 드는 만큼 꼭 교환학생에 도전해 보셨으면 좋겠습니다.',
         '교환학생 오기에 아인트호벤은 정말 좋은 도시입니다. 대도시는 아니지만 웬만한 브랜드나 시설은 다 있고 저가 항공사가 많이 취항하는 공항도 있어 여행 다니기에 좋습니다. 무엇보다 학생들과 청년들이 많이 살아서 젊은 분위기이고, 동네가 깨끗하며 치안도 좋아 안전합니다. 교환학생을 고민하신다면 꼭 가보라고 추천 드리고 싶습니다. 한 학기 동안 많은 것을 배우고 더 넓은 세상을 경험할 수 있었습니다. 외국에서, 특히 학생신분으로 살아본 것은 정말 특별하고 유익한 경험이 되었을 거라고 생각합니다.']

for doc in tfidfScorer(corpus):
    print('====== document ======')
    print(sorted(set(doc), key=lambda x: x[1], reverse=True))

['소문', '네덜란드', '비바람', '많다', '나라', '어디', '가든', '자전거', '타다', '되다', '대부분', '오다', '우비', '챙기다', '가다', '살다', '추천', '하다', '네덜란드', '더치', '언어', '있다', '영어', '가장', '쓰다', '나라', '생활', '하다', '있다', '언어', '크다', '불편하다', '없다', '한국', '생활', '매우', '바쁘다', '정신', '없다', '통학', '하다', '학기', '이면', '출근', '시간', '지하철', '타다', '하다', '않다', '생활', '하다', '되다', '네덜란드', '교환학생', '하다', '여유', '평화롭다', '생활', '하다', '있다', '되어다', '학교', '수업', '다양하다', '많다', '학업', '하다', '아니다', '하나', '프로젝트', '집중', '하다', '하나', '이나', '다음', '프로젝트', '넘어가다', '이러하다', '학업', '방식', '통해', '많다', '배우다', '있다', '집중', '향상', '하다', '여유', '누리다', '학업', '전념', '하다', '있다', '생활', '하다', '되어다']
['개인', '학교', '수업', '통해', '지식', '측면', '크게', '얻다', '가다', '없다', '같다', '네덜란드', '지리', '특성', '변국', '자유롭다', '여행', '다니다', '있다', '철도', '시설', '자다', '갖추다', '있다', '근교', '도시', '방문', '하다', '편하다', '외국인', '친구', '교류', '하다', '기회', '만들다', '있다', '가장', '즐겁다', '요소', '들이다', '실제', '주말', '새롭다', '사귀다', '친구', '로테르담', '헤이그', '주변', '도시', '기차', '타고', '여행', '떠나다', '가을', '방학', '크리스마스', '방학', '프랑스', '독일', '스웨덴', '스위스', 

### 중간 결론
문서 기준 TF가 아니라 문서집합 기준 TF를 구해야 의미적으로 더 맞을 것

In [19]:
test = [['a', 'b', 'c'], ['d', 'e']]
test[0] + test[1]

['a', 'b', 'c', 'd', 'e']